version: "3.7"
services:
  api:
    container_name: api_mongo
    restart: always
    build: 
      context: ./api
    ports: 
      - "3000:3000"
    links: 
      - mongo
    depends_on:
      - mongo
      - nats
  data_broadcast:
    container_name: data_bcast
    build:
      context: ./vehicle-data-generator
    depends_on:
      - api
      - nats
  websocket_api:
    container_name: ws_api
    build:
      context: ./ws_api
    ports:
      - "8080:8080"
    depends_on:
      - nats
    environment:
      - mode=${MODE}
  mongo:
    container_name: mongo_dev
    restart: always
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./mongo_data:/var/lib/mongo/data
  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
