version: "3.7"
services:
  websocket_client:
    # container_name: ws_client
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      placement:
        constraints: [node.role == manager]
    build:
      context: ./websocket_client_test
    depends_on:
      - websocket_api
    environment:
      - mode=${MODE}
  data_broadcast:
    container_name: data_bcast
    build:
      context: ./vehicle-data-generator
    depends_on:
      - nats
    environment:
      - mode=${MODE}
  websocket_api:
    container_name: ws_api
    build:
      context: ./ws_api
    ports:
      - "8080:8080"
    depends_on:
      - nats
    environment:
      - mode=${MODE}
  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
